<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        //create table
        Schema::create('dxcc_ref', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('dxcc');
            $table->string('prefix', 20);
            $table->string('name', 100);
            $table->string('cont', 6);
            $table->string('itu', 20);
            $table->string('waz', 20);
        });

        //Fill reference table via DB Statements because we have no Models for it - table only for statistics reasons
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (0, 'UNKNOWN', 'UNKNOWN', '', '', '');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (246, '1A', 'Sovereign Military Order of Malta', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (247, '1S', 'Spratly Islands', 'AS', '50', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (260, '3A', 'Monaco', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (4, '3B6', 'Agalega & Saint Brandon Is.', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (165, '3B8', 'Mauritius', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (207, '3B9', 'Rodrigues Island', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (49, '3C', 'Equatorial Guinea', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (195, '3C0', 'Pagalu (Annobon) Island', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (176, '3D2', 'Fiji', 'OC', '56', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (489, '3D2(C)', 'Conway Reef (Ceva-I-Ra)', 'OC', '56', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (460, '3D2(R)', 'Rotuma Island', 'OC', '56', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (468, '3DA', 'The Kingdom of Eswatini (Swaziland)', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (474, '3V', 'Tunisia', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (293, '3W', 'Viet Nam', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (107, '3X', 'Guinea', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (24, '3Y(B)', 'Bouvet Island', 'AN', '67', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (199, '3Y(P)', 'Peter I. Island', 'AN', '72', '12');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (18, '4J', 'Azerbaijan', 'AS', '29', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (75, '4L', 'Georgia', 'AS', '29', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (514, '4O', 'Montenegro', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (315, '4S', 'Sri Lanka (Ceylon)', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (117, '4U(I)', 'ITU HQ Geneva', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (289, '4U(U)', 'UN HQ ARC New York (USA)', 'NA', '08', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (511, '4W', 'Timor - Leste', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (336, '4X', 'Israel', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (436, '5A', 'Libya', 'AF', '38', '34');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (215, '5B', 'Cyprus', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (470, '5H', 'Tanzania', 'AF', '53', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (450, '5N', 'Nigeria', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (438, '5R', 'Madagascar (Malagasy Rep.)', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (444, '5T', 'Mauritania', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (187, '5U', 'Niger', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (483, '5V', 'Togo', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (190, '5W', 'Samoa', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (286, '5X', 'Uganda', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (430, '5Z', 'Kenya', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (456, '6W', 'Senegal', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (82, '6Y', 'Jamaica', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (492, '7O', 'Yemen', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (432, '7P', 'Lesotho', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (440, '7Q', 'Malawi', 'AF', '53', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (400, '7X', 'Algeria', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (62, '8P', 'Barbados', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (159, '8Q', 'Maldives', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (129, '8R', 'Guyana', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (497, '9A', 'Croatia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (424, '9G', 'Ghana', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (257, '9H', 'Malta', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (482, '9J', 'Zambia', 'AF', '53', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (348, '9K', 'Kuwait', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (458, '9L', 'Sierra Leone', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (299, '9M2', 'West Malaysia', 'AS', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (46, '9M6', 'East Malaysia', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (369, '9N', 'Nepal', 'AS', '42', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (414, '9Q', 'Democratic Republic of the Congo', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (404, '9U', 'Burundi', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (381, '9V', 'Singapore', 'AS', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (454, '9X', 'Rwanda', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (90, '9Y', 'Trinidad & Tobago', 'SA', '11', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (402, 'A2', 'Botswana (Bechuanaland)', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (160, 'A3', 'Tonga', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (370, 'A4', 'Oman', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (306, 'A5', 'Bhutan', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (391, 'A6', 'United Arab Emirates', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (376, 'A7', 'Qatar', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (304, 'A9', 'Bahrain', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (372, 'AP', 'Pakistan', 'AS', '41', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (506, 'BS7H', 'Scarborough (Huang Yan Dao) Reef', 'AS', '50', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (386, 'BV', 'Taiwan (Formosa)', 'AS', '44', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (505, 'BV9P', 'Pratas (Tung Sha Dao) Island', 'AS', '44', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (318, 'BY', 'China', 'AS', '44', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (157, 'C2', 'Nauru', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (203, 'C3', 'Andorra', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (422, 'C5', 'The Gambia', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (60, 'C6', 'Bahamas', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (181, 'C9', 'Mozambique', 'AF', '53', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (112, 'CE', 'Chile', 'SA', '14', '12');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (47, 'CE0(A)', 'Easter Islands (Rapa Nui)', 'SA', '63', '12');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (217, 'CE0(X)', 'San Felix & San Ambrosio Islands', 'SA', '14', '12');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (125, 'CE0(Z)', 'Juan Fernandez Islands', 'SA', '14', '12');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (13, 'CE9', 'Antarctica', 'AN', '73', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (446, 'CN', 'Morocco', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (70, 'CO', 'Cuba', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (104, 'CP', 'Bolivia', 'SA', '12', '10');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (272, 'CT', 'Portugal', 'EU', '37', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (149, 'CT8', 'Azores Islands', 'EU', '36', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (256, 'CT9', 'Madeira Islands', 'AF', '36', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (144, 'CX', 'Uruguay', 'SA', '14', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (211, 'CY0', 'Sable Island', 'NA', '09', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (252, 'CY9', 'Saint Paul Island', 'NA', '09', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (401, 'D2', 'Angola', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (409, 'D4', 'Cape Verde', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (411, 'D6', 'Comoros', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (230, 'DL', 'Federal Republic of Germany', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (375, 'DU', 'Philippines', 'OC', '50', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (51, 'E3', 'Eritrea', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (510, 'E4', 'Palestine', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (191, 'E51(N)', 'North Cook Islands', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (234, 'E51(S)', 'South Cook Islands', 'OC', '63', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (188, 'E6', 'Niue', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (501, 'E7', 'Bosnia-Herzegovina', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (281, 'EA', 'Spain', 'EU', '37', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (21, 'EA6', 'Balearic Islands', 'EU', '37', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (29, 'EA8', 'Canary Islands', 'AF', '36', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (32, 'EA9', 'Ceuta & Melilla', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (245, 'EI', 'Ireland', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (14, 'EK', 'Armenia', 'AS', '29', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (434, 'EL', 'Liberia', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (330, 'EP', 'Iran', 'AS', '40', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (179, 'ER', 'Moldova', 'EU', '29', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (52, 'ES', 'Estonia', 'EU', '29', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (53, 'ET', 'Ethiopia', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (27, 'EU', 'Belarus', 'EU', '29', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (135, 'EX', 'Kyrgyzstan', 'AS', '31', '17');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (262, 'EY', 'Tajikistan', 'AS', '30', '17');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (280, 'EZ', 'Turkmenistan', 'AS', '30', '17');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (227, 'F', 'France', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (79, 'FG', 'Guadeloupe Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (169, 'FH', 'Mayotte', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (516, 'FJ', 'Saint Barthelemy (Saint Bart\'s) Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (162, 'FK', 'New Caledonia', 'OC', '56', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (512, 'FK(C)', 'Chesterfield Islands', 'OC', '56', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (84, 'FM', 'Martinique', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (175, 'FO', 'French Polynesia', 'OC', '63', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (508, 'FO(A)', 'Austral Islands', 'OC', '63', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (36, 'FO(C)', 'Clipperton Island', 'NA', '10', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (509, 'FO(M)', 'Marquesas Islands', 'OC', '63', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (277, 'FP', 'Saint Pierre & Miquelon', 'NA', '09', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (453, 'FR', 'Reunion', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (213, 'FS', 'Saint Martin Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (99, 'FT(G)', 'Glorioso Island (Isles Glorieuses)', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (124, 'FT(J)', 'Juan de Nova, Europa', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (276, 'FT(T)', 'Tromelin Island', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (41, 'FT(W)', 'Crozet Island', 'AF', '68', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (131, 'FT(X)', 'Kerguelen Islands', 'AF', '68', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (10, 'FT(Z)', 'Amsterdam & Saint Paul Islands', 'AF', '68', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (298, 'FW', 'Wallis & Futuna Islands', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (63, 'FY', 'French Guiana', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (223, 'G', 'England', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (114, 'GD', 'Isle of Man', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (265, 'GI', 'Northern Ireland', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (122, 'GJ', 'Jersey', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (279, 'GM', 'Scotland', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (106, 'GU', 'Guernsey', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (294, 'GW', 'Wales', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (185, 'H4', 'Solomon Islands', 'OC', '51', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (507, 'H40', 'Temotu Province', 'OC', '51', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (239, 'HA', 'Hungary', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (287, 'HB', 'Switzerland', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (251, 'HB0', 'Liechtenstein', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (120, 'HC', 'Ecuador', 'SA', '12', '10');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (71, 'HC8', 'Galapagos Islands', 'SA', '12', '10');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (78, 'HH', 'Haiti', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (72, 'HI', 'Dominican Rep.', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (116, 'HK', 'Colombia', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (216, 'HK0(A)', 'San Andres & Providencia', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (161, 'HK0(M)', 'Malpelo Island', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (137, 'HL', 'Republic of Korea', 'AS', '44', '25');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (88, 'HP', 'Panama', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (80, 'HR', 'Honduras', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (387, 'HS', 'Thailand', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (295, 'HV', 'Vatican', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (378, 'HZ', 'Saudi Arabia', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (248, 'I', 'Italy', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (225, 'IS', 'Sardinia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (382, 'J2', 'Djibouti', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (77, 'J3', 'Grenada', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (109, 'J5', 'Guinea-Bissau', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (97, 'J6', 'Saint Lucia', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (95, 'J7', 'Dominica', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (98, 'J8', 'Saint Vincent & Grenadines', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (339, 'JA', 'Japan', 'AS', '45', '25');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (177, 'JD1(M)', 'Minami Torishima (Marcus Island)', 'OC', '90', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (192, 'JD1(O)', 'Ogasawara (Bonin & Volcano Isl., Iwo Jima)', 'AS', '45', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (363, 'JT', 'Mongolia', 'AS', '32-33', '23');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (259, 'JW', 'Spitsbergen (Svalbard)', 'EU', '18', '40');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (118, 'JX', 'Jan Mayen Island', 'EU', '18', '40');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (342, 'JY', 'Jordan', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (105, 'KG4', 'Guantanamo Bay', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (166, 'KH0', 'Mariana Islands', 'OC', '64', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (20, 'KH1', 'Baker & Howland Islands', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (103, 'KH2', 'Guam', 'OC', '64', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (123, 'KH3', 'Johnston Islands', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (174, 'KH4', 'Midway Island', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (197, 'KH5', 'Palmyra & Jarvis Islands', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (110, 'KH6', 'Hawaii', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (138, 'KH7(K)', 'Kure Island', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (9, 'KH8', 'American Samoa', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (515, 'KH8(S)', 'Swain\'s Island', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (297, 'KH9', 'Wake Island', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (6, 'KL', 'Alaska', 'NA', '1', '01');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (182, 'KP1', 'Navassa Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (285, 'KP2', 'Virgin Islands', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (202, 'KP4', 'Puerto Rico', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (43, 'KP5', 'Desecheo Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (266, 'LA', 'Norway', 'EU', '18', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (100, 'LU', 'Argentina', 'SA', '14', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (254, 'LX', 'Luxembourg', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (146, 'LY', 'Lithuania', 'EU', '29', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (212, 'LZ', 'Bulgaria', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (136, 'OA', 'Peru', 'SA', '12', '10');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (354, 'OD', 'Lebanon', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (206, 'OE', 'Austria', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (224, 'OH', 'Finland', 'EU', '18', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (5, 'OH0', 'Aland Islands', 'EU', '18', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (167, 'OJ0', 'Market Reef', 'EU', '18', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (503, 'OK', 'Czech Republic', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (504, 'OM', 'Slovak Republic', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (209, 'ON', 'Belgium', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (237, 'OX', 'Greenland (Kalaallit Nunaat)', 'NA', '05', '40');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (222, 'OY', 'Faeroe Islands', 'EU', '18', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (221, 'OZ', 'Denmark', 'EU', '18', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (163, 'P2', 'Papua New Guinea', 'OC', '51', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (91, 'P4', 'Aruba', 'SA', '11', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (344, 'P5', 'DPR of Korea', 'AS', '44', '25');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (263, 'PA', 'Netherlands', 'EU', '27', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (517, 'PJ2', 'Curacao', 'SA', '11', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (520, 'PJ4', 'Bonaire', 'SA', '11', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (519, 'PJ6', 'Saba & Saint Eustatius', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (518, 'PJ7', 'Sint Maarten', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (108, 'PY', 'Brazil', 'SA', '15', '11');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (56, 'PY0(F)', 'Fernando de Noronha', 'SA', '13', '11');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (253, 'PY0(S)', 'Saint Peter & Saint Paul Rocks', 'SA', '13', '11');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (273, 'PY0(T)', 'Trindade & Martim Vaz Islands', 'SA', '15', '11');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (140, 'PZ', 'Suriname', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (61, 'R1(F)', 'Franz Josef Land, [Russian Territory] (FJ)', 'EU', '75', '40');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (302, 'S0', 'Western Sahara', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (305, 'S2', 'Bangladesh (East Pakistan)', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (499, 'S5', 'Slovenia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (379, 'S7', 'Seychelles', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (219, 'S9', 'Sao Tome & Principe', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (284, 'SM', 'Sweden', 'EU', '18', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (269, 'SP', 'Poland', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (466, 'ST', 'Sudan', 'AF', '48', '34');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (478, 'SU', 'Egypt', 'AF', '38', '34');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (236, 'SV', 'Greece', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (180, 'SV(A)', 'Mount Athos', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (45, 'SV5', 'Dodecanese', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (40, 'SV9', 'Crete', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (282, 'T2', 'Tuvalu', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (301, 'T30', 'West Kiribati (Gilbert Is.)', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (31, 'T31', 'Central Kiribati (British Phoenix Is.)', 'OC', '62', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (48, 'T32', 'East Kiribati (Line Is.)', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (490, 'T33', 'Banaba (Ocean) Island', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (232, 'T5', 'Somalia', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (278, 'T7', 'San Marino', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (22, 'T8', 'Republic of Palau (Belau)', 'OC', '64', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (390, 'TA', 'Turkey', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (242, 'TF', 'Iceland', 'EU', '17', '40');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (76, 'TG', 'Guatemala', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (308, 'TI', 'Costa Rica', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (37, 'TI9', 'Cocos Island', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (406, 'TJ', 'Cameroon', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (214, 'TK', 'Corsica', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (408, 'TL', 'Central African Republic', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (412, 'TN', 'Congo', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (420, 'TR', 'Gabon', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (410, 'TT', 'Chad', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (428, 'TU', 'Cote d\'Ivoire', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (416, 'TY', 'Benin', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (442, 'TZ', 'Mali', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (15, 'UA(AS)', 'Russia (Asiatic)', 'AS', '32', '18');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (54, 'UA(EU)', 'Russia (European)', 'EU', '29', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (126, 'UA(K)', 'Kaliningrad (Koenigsberg)', 'EU', '29', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (292, 'UK', 'Uzbekistan', 'AS', '30', '17');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (130, 'UN', 'Kazakhstan', 'AS', '29-31', '17');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (288, 'UT', 'Ukraine', 'EU', '29', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (94, 'V2', 'Antigua & Barbuda', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (66, 'V3', 'Belize', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (249, 'V4', 'Saint Kitts & Nevis', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (464, 'V5', 'Namibia', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (173, 'V6', 'Federated States of Micronesia', 'OC', '65', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (168, 'V7', 'Marshall Islands', 'OC', '65', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (345, 'V8', 'Brunei Darussalam', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (1, 'VE', 'Canada', 'NA', '04', '04');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (150, 'VK', 'Australia', 'OC', '59', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (111, 'VK0(H)', 'Heard Island', 'AN', '68', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (153, 'VK0(M)', 'Macquarie Island', 'AN', '60', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (38, 'VK9(C)', 'Cocos (Keeling) Islands', 'OC', '54', '29');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (147, 'VK9(L)', 'Lord Howe Island', 'OC', '60', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (171, 'VK9(M)', 'Mellish Reef', 'OC', '56', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (189, 'VK9(N)', 'Norfolk Island', 'OC', '60', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (303, 'VK9(W)', 'Willis Island', 'OC', '55', '30');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (35, 'VK9(X)', 'Christmas Island', 'OC', '54', '29');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (235, 'VP0G', 'South Georgia (San Pedro) Islands', 'AN', '73', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (240, 'VP0S', 'South Sandwich Islands', 'AN', '73', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (12, 'VP2E', 'Anguilla', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (96, 'VP2M', 'Montserrat', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (65, 'VP2V', 'British Virgin Islands', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (89, 'VP5', 'Turks & Caicos Islands', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (172, 'VP6', 'Pitcairn Island', 'OC', '63', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (513, 'VP6(D)', 'Ducie Atoll', 'OC', '63', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (141, 'VP8(F)', 'Falkland Islands', 'SA', '16', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (241, 'VP8(H)', 'South Shetland Islands', 'AN', '73', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (238, 'VP8(O)', 'South Orkney Islands', 'AN', '73', '13');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (64, 'VP9', 'Bermuda', 'NA', '11', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (33, 'VQ9', 'Chagos (Diego Garcia Isl.)', 'AF', '41', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (321, 'VR', 'Hong Kong', 'AS', '44', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (324, 'VU', 'India', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (11, 'VU(A)', 'Andaman & Nicobar Islands', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (142, 'VU(L)', 'Laccadive Islands (Lakshadweep)', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (291, 'W', 'United States', 'NA', '08', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (50, 'XE', 'Mexico', 'NA', '10', '06');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (204, 'XF4', 'Revillagigedo', 'NA', '10', '06');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (480, 'XT', 'Burkina Faso (Upper Volta)', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (312, 'XU', 'Cambodia (Kampuchea)', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (143, 'XW', 'Laos', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (152, 'XX', 'Macao', 'AS', '44', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (309, 'XZ', 'Myanmar (Burma)', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (3, 'YA', 'Afghanistan', 'AS', '40', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (327, 'YB', 'Indonesia', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (333, 'YI', 'Iraq', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (158, 'YJ', 'Vanuatu (New Hebrides)', 'OC', '56', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (384, 'YK', 'Syria', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (145, 'YL', 'Latvia', 'EU', '29', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (86, 'YN', 'Nicaragua', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (275, 'YO', 'Romania', 'EU', '28', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (74, 'YS', 'El Salvador', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (296, 'YU', 'Serbia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (148, 'YV', 'Venezuela', 'SA', '12', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (17, 'YV0', 'Aves Island', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (452, 'Z2', 'Zimbabwe (Southern Rhodesia)', 'AF', '53', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (502, 'Z3', 'North Macedonia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (522, 'Z6', 'Republic of Kosovo', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (521, 'Z8', 'Republic of South Sudan', 'AF', '48', '34');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (7, 'ZA', 'Albania', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (233, 'ZB', 'Gibraltar', 'EU', '37', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (283, 'ZC4', 'UK Sovereign Base Areas on Cyprus', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (250, 'ZD7', 'Saint Helena Island', 'AF', '66', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (205, 'ZD8', 'Ascension Island', 'AF', '66', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (274, 'ZD9', 'Tristan da Cunha & Gough Islands', 'AF', '66', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (69, 'ZF', 'Cayman Islands', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (270, 'ZK3', 'Tokelau Island', 'OC', '62', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (170, 'ZL', 'New Zealand', 'OC', '60', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (34, 'ZL7', 'Chatham Island', 'OC', '60', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (133, 'ZL8', 'Kermadec Island', 'OC', '60', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (16, 'ZL9', 'New Zealand Subantarctic Islands', 'OC', '60', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (132, 'ZP', 'Paraguay', 'SA', '14', '11');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (462, 'ZS', 'South Africa', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (201, 'ZS(M)', 'Prince Edward & Marion Islands', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (23, '1B9*', 'Blenheim Reef', 'AF', '41', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (93, '1G5*', 'Geyser Reef', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (178, '1M4*', 'Minerva Reef', 'OC', '62', '32');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (154, '4W1*', 'Yemen Arab Republic', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (194, '7J1(O)*', 'Okino Tori-shima (Parece Vela - Douglas Reef)', 'AS', '45', '27');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (226, '8Z4*', 'Saudi Arabia/Iraq Neutral Zone', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (68, '8Z5*', 'Kuwait/Saudi Arabia Neutral Zone', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (210, '9S4*', 'Saar', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (208, '9U5*', 'Ruanda-Urundi', 'AF', '52', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (2, 'A1*', 'Abu Ail, Jabal at Tair', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (231, 'AC3*', 'Sikkim', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (268, 'AC4*', 'Tibet', 'AS', '41', '23');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (164, 'C9*', 'Manchuria', 'AS', '33', '24');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (264, 'CN2*', 'Tangier', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (200, 'CR8*', 'Portuguese Timor', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (42, 'CR8(D)*', 'Damao, Diu', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (101, 'CR8(G)*', 'Goa', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (81, 'DL*', 'Germany', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (229, 'DM*', 'German Democratic Republic', 'EU', '28', '14');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (113, 'EA9*', 'Ifni (Rio de Oro)', 'AF', '37', '33');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (59, 'FF*', 'French West Africa', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (39, 'FH(C)*', 'Comoros', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (58, 'FI8*', 'French Indo-China', 'AS', '49', '26');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (67, 'FN8*', 'French India', 'AS', '41', '22');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (57, 'FQ8*', 'French Equatorial Africa', 'AF', '47', '36');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (19, 'HK0(B)*', 'Bajo Nuevo', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (228, 'HK0(S)*', 'Serrana Bank & Roncador Cay', 'NA', '11', '07');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (271, 'I1*', 'Trieste', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (115, 'I5*', 'Italian Somaliland', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (193, 'J9*', 'Okinawa (Ryukyu Is)', 'OC', '45', '25');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (184, 'JZ0*', 'Netherlands N. Guinea', 'OC', '51', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (134, 'KH5(K)*', 'Kingman Reef', 'OC', '61', '31');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (193, 'KR(O)*', 'Okinawa (Ryukyu Is)', 'OC', '45', '25');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (261, 'KS4(B)*', 'Swan Island', 'NA', '11', '7');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (28, 'KZ5*', 'Canal Zone', 'NA', '11', '7');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (218, 'OK*', 'Czechoslovakia', 'EU', '28', '15');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (198, 'P2*', 'Papua Territory', 'OC', '51', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (267, 'P2*', 'Territory of New Guinea', 'OC', '51', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (85, 'PJ2*', 'Netherlands Antilles, Curacao', 'SA', '11', '09');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (255, 'PJ7*', 'Sint Maarten', 'NA', '11', '08');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (119, 'PK1*', 'Java', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (258, 'PK4*', 'Sumatra', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (183, 'PK5*', 'Dutch Borneo', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (30, 'PK6*', 'Celebes & Molucca Islands', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (151, 'R1(M)*', 'Malyj Vysotskij Island, [Russian Territory] (MV)', 'EU', '29', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (244, 'ST0*', 'Southern Sudan', 'AF', '47-48', '34');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (128, 'UN1*', 'Karelo-Finnish Republic', 'EU', '19', '16');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (186, 'VO*', 'Newfoundland, Labrador', 'NA', '9', '05');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (307, 'VQ1*', 'Zanzibar', 'AF', '53', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (26, 'VQ6*', 'British Somaliland', 'AF', '48', '37');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (8, 'VQ9(A)*', 'Aldabra Isl.', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (44, 'VQ9(D)*', 'Desroches Isl.', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (55, 'VQ9(F)*', 'Farquhar Isl.', 'AF', '53', '39');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (155, 'VS2*', 'Malaya', 'AS', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (220, 'VS4*', 'Sarawak', 'AS', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (243, 'VS9A*', 'Peoples Dem. Rep. of Yemen', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (139, 'VS9H*', 'Kuria Muria Is.', 'AS', '39', '21');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (127, 'VS9K*', 'Kamaran Is.', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (25, 'ZC5*', 'British North Borneo & Labuan', 'OC', '54', '28');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (196, 'ZC6*', 'Palestine', 'AS', '39', '20');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (102, 'ZD4*', 'Gold Coast, Togoland', 'AF', '46', '35');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (493, 'ZS(P)*', 'Penguin Island', 'AF', '57', '38');");
        DB::statement("INSERT INTO `dxcc_ref` (`dxcc`, `prefix`, `name`, `cont`, `itu`, `waz`) VALUES (488, 'ZS(W)*', 'Walvis Bay', 'AF', '57', '38');");
                
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('dxcc_ref');
    }
};
